[package]
name = "demo-app"
version = "1.0.0"
edition = "2021"
authors = ["Djkáťo <djkatovfx@gmail.com>"]
[[bin]]
name = "demo_app"
path = "src/main.rs"

[[bin]]
name = "demo_app_installer"
path = "installer/installer.rs"

[dependencies]
installer_lite = { version = "*",path = "../"}